#!/bin/bash

echo "🗄️ Flower Fairies Database Setup (Cloud Shell)"
echo "=============================================="
echo ""
echo "Since psql is not installed locally, here are your options:"
echo ""
echo "OPTION 1: Use AWS CloudShell (Recommended)"
echo "==========================================="
echo "1. Go to: https://console.aws.amazon.com/cloudshell"
echo "2. Upload these files:"
echo "   - server/db/schema.sql"
echo "   - server/db/seed.sql"
echo "3. Run these commands:"
echo ""
echo "# Install PostgreSQL client"
echo "sudo yum install postgresql15 -y"
echo ""
echo "# Create database"
echo "PGPASSWORD='FlowerFairies2024!' psql \\"
echo "  -h flower-fairies-db.coleey2ae5t5.us-east-1.rds.amazonaws.com \\"
echo "  -U postgres \\"
echo "  -c 'CREATE DATABASE flower_fairies;'"
echo ""
echo "# Run schema"
echo "PGPASSWORD='FlowerFairies2024!' psql \\"
echo "  -h flower-fairies-db.coleey2ae5t5.us-east-1.rds.amazonaws.com \\"
echo "  -U postgres \\"
echo "  -d flower_fairies \\"
echo "  -f schema.sql"
echo ""
echo "# Run seed data"
echo "PGPASSWORD='FlowerFairies2024!' psql \\"
echo "  -h flower-fairies-db.coleey2ae5t5.us-east-1.rds.amazonaws.com \\"
echo "  -U postgres \\"
echo "  -d flower_fairies \\"
echo "  -f seed.sql"
echo ""
echo "OPTION 2: Use a PostgreSQL GUI"
echo "=============================="
echo "1. Download TablePlus, pgAdmin, or DBeaver"
echo "2. Connect with:"
echo "   Host: flower-fairies-db.coleey2ae5t5.us-east-1.rds.amazonaws.com"
echo "   Port: 5432"
echo "   Username: postgres"
echo "   Password: FlowerFairies2024!"
echo "3. Create database: flower_fairies"
echo "4. Run the SQL files"
echo ""
echo "📱 Your App is Deploying!"
echo "========================"
echo "URL: https://iqwxcnq9v8.us-east-1.awsapprunner.com"
echo ""
echo "Demo Accounts (after DB setup):"
echo "  Admin: admin@flowerfairies.com / admin123"
echo "  Driver: driver1@flowerfairies.com / driver123"
echo "  Customer: customer1@flowerfairies.com / customer123"
